version: '3.8'

services:
  backend:
    build: ./Back-end
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:3000,http://localhost:3001
    volumes:
      - ./Back-end/upload:/app/upload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ecommerce-network

  frontend:
    build: ./Front-end
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ecommerce-network

  admin:
    build: ./Admin
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  uploads:
    driver: local
